-- Supabase Dashboard → SQL Editor에 붙여넣고 Run 하세요.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  user_email text not null,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;

-- 누구나 게시글 목록은 볼 수 있음
create policy "Anyone can read posts"
on public.posts
for select
using (true);

-- 로그인한 사용자만 글쓰기 가능
create policy "Logged in users can insert posts"
on public.posts
for insert
to authenticated
with check (auth.uid() = user_id);

-- 본인이 쓴 글만 수정 가능
create policy "Users can update their own posts"
on public.posts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 본인이 쓴 글만 삭제 가능
create policy "Users can delete their own posts"
on public.posts
for delete
to authenticated
using (auth.uid() = user_id);
